### PR TITLE
added textarea and submit button

### PR DESCRIPTION
**Pull request by Lucas-Erkana**

### CODE REVIEW

**Comment by adel-gu** [comment]
I like that, actually this has to be merged.

**Comment by Lucas-Erkana** [comment]
We didn't add a value to our check boxes. Going to add that now on a
different branch

**Comment by adel-gu** [comment]
Nice observation on check boxes values.

**Comment by Lucas-Erkana** [comment]
Don't want that branch anymore. It screw everything up. I will just delete
it

**Pull request merged**
